version: '3.9'
name: socialmedia
services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: socialmedia
    ports:
      - 5432:5432

  server:
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - database